#!/bin/bash

# todo - makefile

gcc -g -Wall -Igoodbrew -c base.c -o base.o
gcc -g -Wall -Igoodbrew -c graphics.c -o graphics.o
gcc -g -Wall -Igoodbrew -c images.c -o images.o
gcc -g -Wall -Igoodbrew -c paths.c -o paths.o
gcc -g -Wall -Igoodbrew -c useful.c -o useful.o
gcc -g -Wall -Igoodbrew -c text.c -o text.o
ar rcs libgoodbrew.a base.o graphics.o images.o paths.o useful.o text.o